/*******************************************************************************
 * Copyright (c) 2000, 2013 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.summer.sdt.internal.compiler.parser;

/**
 * IMPORTANT NOTE: These constants are dedicated to the internal Scanner implementation.
 * It is mirrored in org.summer.sdt.core.compiler public package where it is API.
 * The mirror implementation is using the backward compatible ITerminalSymbols constant
 * definitions (stable with 2.0), whereas the internal implementation uses TerminalTokens
 * which constant values reflect the latest parser generation state.
 */
/**
 * Maps each terminal symbol in the java-grammar into a unique integer.
 * This integer is used to represent the terminal when computing a parsing action.
 *
 * Disclaimer : These constant values are generated automatically using a Java
 * grammar, therefore their actual values are subject to change if new keywords
 * were added to the language (for instance, 'assert' is a keyword in 1.4).
 */
public interface TerminalTokens {

	// special tokens not part of grammar - not autogenerated
	int TokenNameNotAToken = 0,
		TokenNameWHITESPACE = 1000,
		TokenNameCOMMENT_LINE = 1001,
		TokenNameCOMMENT_BLOCK = 1002,
		TokenNameCOMMENT_JAVADOC = 1003;

    public final static int
	    TokenNameIdentifier = 10,
	    TokenNameabstract = 41,
	    TokenNameboolean = 97,
	    TokenNamebreak = 84,
	    TokenNamebyte = 98,
	    TokenNamecase = 99,
	    TokenNamecatch = 100,
	    TokenNamechar = 101,
	    TokenNameclass = 66,
	    TokenNamecontinue = 85,
	    TokenNameconst = 120,
	    TokenNamedefault = 71,
	    TokenNamedo = 86,
	    TokenNamedouble = 102,
	    TokenNameelse = 111,
	    TokenNameenum = 69,
	    TokenNameevent = 116,
	    TokenNameexport = 121,
	    TokenNameextends = 96,
	    TokenNamefalse = 51,
	    TokenNamefinal = 42,
	    TokenNamefinally = 109,
	    TokenNamefloat = 103,
	    TokenNamefor = 87,
	    TokenNamefunction = 122,
	    TokenNamegoto = 123,
	    TokenNameif = 88,
	    TokenNameimplements = 117,
	    TokenNameimport = 104,
	    TokenNamein = 124,
	    TokenNameinstanceof = 19,
	    TokenNameint = 105,
	    TokenNameinterface = 68,
	    TokenNamelet = 125,
	    TokenNamelong = 106,
	    TokenNamemodule = 94,
	    TokenNamenative = 43,
	    TokenNamenew = 37,
	    TokenNamenull = 52,
	    TokenNamepackage = 95,
	    TokenNameprivate = 44,
	    TokenNameprotected = 45,
	    TokenNamepublic = 46,
	    TokenNamereturn = 89,
	    TokenNameshort = 107,
	    TokenNamestatic = 39,
	    TokenNamestrictfp = 47,
	    TokenNamesuper = 38,
	    TokenNameswitch = 90,
	    TokenNamesynchronized = 40,
	    TokenNamethis = 35,
	    TokenNamethrow = 91,
	    TokenNamethrows = 113,
	    TokenNametransient = 48,
	    TokenNametrue = 53,
	    TokenNametry = 92,
	    TokenNametypeof = 126,
	    TokenNamevoid = 108,
	    TokenNamevolatile = 49,
	    TokenNamewhile = 72,
	    TokenNamePCDATA = 114,
	    TokenNameIntegerLiteral = 54,
	    TokenNameLongLiteral = 55,
	    TokenNameFloatingPointLiteral = 56,
	    TokenNameDoubleLiteral = 57,
	    TokenNameCharacterLiteral = 58,
	    TokenNameStringLiteral = 50,
	    TokenNameCODE_DATA = 118,
	    TokenNamePLUS_PLUS = 1,
	    TokenNameMINUS_MINUS = 2,
	    TokenNameEQUAL_EQUAL = 22,
	    TokenNameLESS_EQUAL = 16,
	    TokenNameGREATER_EQUAL = 17,
	    TokenNameNOT_EQUAL = 23,
	    TokenNameLEFT_SHIFT = 20,
	    TokenNameRIGHT_SHIFT = 14,
	    TokenNameUNSIGNED_RIGHT_SHIFT = 15,
	    TokenNamePLUS_EQUAL = 73,
	    TokenNameMINUS_EQUAL = 74,
	    TokenNameMULTIPLY_EQUAL = 75,
	    TokenNameDIVIDE_EQUAL = 76,
	    TokenNameAND_EQUAL = 77,
	    TokenNameOR_EQUAL = 78,
	    TokenNameXOR_EQUAL = 79,
	    TokenNameREMAINDER_EQUAL = 80,
	    TokenNameLEFT_SHIFT_EQUAL = 81,
	    TokenNameRIGHT_SHIFT_EQUAL = 82,
	    TokenNameUNSIGNED_RIGHT_SHIFT_EQUAL = 83,
	    TokenNameOR_OR = 31,
	    TokenNameAND_AND = 30,
	    TokenNamePLUS = 3,
	    TokenNameMINUS = 4,
	    TokenNameNOT = 61,
	    TokenNameREMAINDER = 8,
	    TokenNameXOR = 27,
	    TokenNameAND = 21,
	    TokenNameMULTIPLY = 7,
	    TokenNameOR = 28,
	    TokenNameTWIDDLE = 62,
	    TokenNameDIVIDE = 9,
	    TokenNameGREATER = 12,
	    TokenNameLESS = 6,
	    TokenNameLPAREN = 18,
	    TokenNameRPAREN = 26,
	    TokenNameLBRACE = 34,
	    TokenNameRBRACE = 32,
	    TokenNameLBRACKET = 11,
	    TokenNameRBRACKET = 65,
	    TokenNameSEMICOLON = 25,
	    TokenNameQUESTION = 29,
	    TokenNameCOLON = 64,
	    TokenNameCOMMA = 33,
	    TokenNameDOT = 5,
	    TokenNameEQUAL = 67,
	    TokenNameAT = 36,
	    TokenNameELLIPSIS = 119,
	    TokenNameARROW = 110,
	    TokenNameCOLON_COLON = 13,
	    TokenNameBeginLambda = 59,
	    TokenNameBeginIntersectionCast = 63,
	    TokenNameBeginTypeArguments = 93,
	    TokenNameElidedSemicolonAndRightBrace = 70,
	    TokenNameCLOSE_TAG = 115,
	    TokenNameCLOSE_ELEMENT = 112,
	    TokenNameAT308 = 24,
	    TokenNameEOF = 60,
		TokenNameERROR = 127;

}
