/*******************************************************************************
 * Copyright (c) 2000, 2013 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.summer.sdt.internal.compiler.parser;

/**
 * IMPORTANT NOTE: These constants are dedicated to the internal Scanner implementation.
 * It is mirrored in org.eclipse.jdt.core.compiler public package where it is API.
 * The mirror implementation is using the backward compatible ITerminalSymbols constant
 * definitions (stable with 2.0), whereas the internal implementation uses TerminalTokens
 * which constant values reflect the latest parser generation state.
 */
/**
 * Maps each terminal symbol in the java-grammar into a unique integer.
 * This integer is used to represent the terminal when computing a parsing action.
 *
 * Disclaimer : These constant values are generated automatically using a Java
 * grammar, therefore their actual values are subject to change if new keywords
 * were added to the language (for instance, 'assert' is a keyword in 1.4).
 */
public interface TerminalTokens {

	// special tokens not part of grammar - not autogenerated
	int TokenNameNotAToken = 0,
		TokenNameWHITESPACE = 1000,
		TokenNameCOMMENT_LINE = 1001,
		TokenNameCOMMENT_BLOCK = 1002,
		TokenNameCOMMENT_JAVADOC = 1003;

	public final static int
	TokenNameIdentifier = 22,
    TokenNameabstract = 60,
    TokenNameassert = 81,
    TokenNameboolean = 33,
    TokenNamebreak = 82,
    TokenNamebyte = 34,
    TokenNamecase = 109,
    TokenNamecatch = 106,
    TokenNamechar = 35,
    TokenNameclass = 77,
    TokenNamecontinue = 83,
    TokenNameconst = 123,
    TokenNamedefault = 78,
    TokenNamedo = 84,
    TokenNamedouble = 36,
    TokenNameelse = 112,
    TokenNameenum = 91,
    TokenNameextends = 105,
    TokenNamefalse = 48,
    TokenNamefinal = 61,
    TokenNamefinally = 110,
    TokenNamefloat = 37,
    TokenNamefor = 85,
    TokenNamegoto = 124,
    TokenNameif = 86,
    TokenNameimplements = 121,
    TokenNameimport = 107,
    TokenNameinstanceof = 16,
    TokenNameint = 38,
    TokenNameinterface = 79,
    TokenNamelong = 39,
    TokenNamenative = 62,
    TokenNamenew = 45,
    TokenNamenull = 49,
    TokenNamepackage = 93,
    TokenNameprivate = 63,
    TokenNameprotected = 64,
    TokenNamepublic = 65,
    TokenNamereturn = 87,
    TokenNameshort = 40,
    TokenNamestatic = 58,
    TokenNamestrictfp = 66,
    TokenNamesuper = 44,
    TokenNameswitch = 88,
    TokenNamesynchronized = 59,
    TokenNamethis = 43,
    TokenNamethrow = 89,
    TokenNamethrows = 114,
    TokenNametransient = 67,
    TokenNametrue = 50,
    TokenNametry = 90,
    TokenNamevoid = 41,
    TokenNamevolatile = 68,
    TokenNamewhile = 80,
    TokenNameref = 125,
    TokenNameout = 126,
    TokenNameget = 115,
    TokenNameset = 116,
    TokenNameadd = 117,
    TokenNameremove = 118,
    TokenNameevent = 119,
    TokenNamemodule = 108,
    TokenNameexport = 127,
    TokenNamefunction = 42,
    TokenNameIntegerLiteral = 51,
    TokenNameLongLiteral = 52,
    TokenNameFloatingPointLiteral = 53,
    TokenNameDoubleLiteral = 54,
    TokenNameCharacterLiteral = 55,
    TokenNameStringLiteral = 47,
    TokenNamePLUS_PLUS = 2,
    TokenNameMINUS_MINUS = 3,
    TokenNameEQUAL_EQUAL = 19,
    TokenNameLESS_EQUAL = 13,
    TokenNameGREATER_EQUAL = 14,
    TokenNameNOT_EQUAL = 20,
    TokenNameLEFT_SHIFT = 18,
    TokenNameRIGHT_SHIFT = 15,
    TokenNameUNSIGNED_RIGHT_SHIFT = 17,
    TokenNamePLUS_EQUAL = 94,
    TokenNameMINUS_EQUAL = 95,
    TokenNameMULTIPLY_EQUAL = 96,
    TokenNameDIVIDE_EQUAL = 97,
    TokenNameAND_EQUAL = 98,
    TokenNameOR_EQUAL = 99,
    TokenNameXOR_EQUAL = 100,
    TokenNameREMAINDER_EQUAL = 101,
    TokenNameLEFT_SHIFT_EQUAL = 102,
    TokenNameRIGHT_SHIFT_EQUAL = 103,
    TokenNameUNSIGNED_RIGHT_SHIFT_EQUAL = 104,
    TokenNameOR_OR = 29,
    TokenNameAND_AND = 28,
    TokenNamePLUS = 4,
    TokenNameMINUS = 5,
    TokenNameNOT = 70,
    TokenNameREMAINDER = 9,
    TokenNameXOR = 23,
    TokenNameAND = 21,
    TokenNameMULTIPLY = 8,
    TokenNameOR = 25,
    TokenNameTWIDDLE = 71,
    TokenNameDIVIDE = 10,
    TokenNameGREATER = 12,
    TokenNameLESS = 11,
    TokenNameLPAREN = 24,
    TokenNameRPAREN = 27,
    TokenNameLBRACE = 46,
    TokenNameRBRACE = 31,
    TokenNameLBRACKET = 6,
    TokenNameRBRACKET = 72,
    TokenNameSEMICOLON = 30,
    TokenNameQUESTION = 26,
    TokenNameCOLON = 69,
    TokenNameCOMMA = 32,
    TokenNameDOT = 1,
    TokenNameEQUAL = 76,
    TokenNameAT = 57,
    TokenNameELLIPSIS = 122,
    TokenNameARROW = 111,
    TokenNameCOLON_COLON = 7,
    TokenNameBeginLambda = 56,
    TokenNameBeginIntersectionCast = 73,
    TokenNameBeginTypeArguments = 92,
    TokenNameElidedSemicolonAndRightBrace = 75,
    TokenNameCLOSE_TAG = 113,
    TokenNameCLOSE_ELEMENT = 120,
    TokenNameEOF = 74,
	TokenNameERROR = 128;
}
